# Test Configuration
base.url=http://lms.rivia.internal
browser=chrome
implicit.wait=10
explicit.wait=15

# Test Users
admin.email=admin@rivia.com
admin.password=Admin@123
student.email=student@rivia.com
student.password=Student@123

# Reporting
report.path=target/reports
screenshot.path=target/screenshots
